
services:
  frontend:
    build:
      context: ./
      args:
        - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"