version: '3'

services:
  frontend:
    build:
      context: ./frontend-2173
      args:
        - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
        - VITE_API_URL=${VITE_API_URL:-https://noamsito.lat}
    ports:
      - "80:80"